{'album': {'album_type': 'single',
           'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5Q8asiEUYLobc6DvKIsqOP'},
                        'href': 'https://api.spotify.com/v1/artists/5Q8asiEUYLobc6DvKIsqOP',
                        'id': '5Q8asiEUYLobc6DvKIsqOP',
                        'name': 'Claudia Isaki',
                        'type': 'artist',
                        'uri': 'spotify:artist:5Q8asiEUYLobc6DvKIsqOP'}],
           'external_urls': {'spotify': 'https://open.spotify.com/album/2YwdWf8D4cHlmwVSCEUMEh'},
           'href': 'https://api.spotify.com/v1/albums/2YwdWf8D4cHlmwVSCEUMEh',
           'id': '2YwdWf8D4cHlmwVSCEUMEh',
           'images': [{'height': 640,
                       'url': 'https://i.scdn.co/image/ab67616d0000b2737028fc3c90901ee81a6f88d5',
                       'width': 640},
                      {'height': 300,
                       'url': 'https://i.scdn.co/image/ab67616d00001e027028fc3c90901ee81a6f88d5',
                       'width': 300},
                      {'height': 64,
                       'url': 'https://i.scdn.co/image/ab67616d000048517028fc3c90901ee81a6f88d5',
                       'width': 64}],
           'name': 'Golden Hour',
           'release_date': '2020-10-02',
           'release_date_precision': 'day',
           'total_tracks': 5,
           'type': 'album',
           'uri': 'spotify:album:2YwdWf8D4cHlmwVSCEUMEh'},
 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5Q8asiEUYLobc6DvKIsqOP'},
              'href': 'https://api.spotify.com/v1/artists/5Q8asiEUYLobc6DvKIsqOP',
              'id': '5Q8asiEUYLobc6DvKIsqOP',
              'name': 'Claudia Isaki',
              'type': 'artist',
              'uri': 'spotify:artist:5Q8asiEUYLobc6DvKIsqOP'}],
 'disc_number': 1,
 'duration_ms': 189133,
 'episode': False,
 'explicit': False,
 'external_ids': {'isrc': 'QZK6F2007074'},
 'external_urls': {'spotify': 'https://open.spotify.com/track/4tP29y2nwWTdGvo0QR7gpF'},
 'href': 'https://api.spotify.com/v1/tracks/4tP29y2nwWTdGvo0QR7gpF',
 'id': '4tP29y2nwWTdGvo0QR7gpF',
 'is_local': False,
 'is_playable': True,
 'name': 'Bedside Table',
 'popularity': 37,
 'preview_url': 'https://p.scdn.co/mp3-preview/864afe14a73f3f7a4682f587147759cfe79f945b?cid=d46569c22e364e279530ee57b31a885e',  
 'track': True,
 'track_number': 4,
 'type': 'track',
 'uri': 'spotify:track:4tP29y2nwWTdGvo0QR7gpF'}